global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'yourgmail@gmail.com'
  smtp_auth_username: 'yourgmail@gmail.com'
  smtp_auth_password: 'app-password'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: 'yourgmail@gmail.com'
    send_resolved: true
