apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-failure-rules
  namespace: monitoring
spec:
  groups:
  - name: pod-failure-alerts
    rules:
    - alert: PodFailure
      expr: increase(kube_pod_container_status_restarts_total[2m]) > 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod failure detected"
        description: "Pod(s) are in CrashLoopBackOff for more than 2 minutes."
