apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-kill-schedule
  namespace: chaos-mesh
spec:
  schedule: '@every 1m'
  type: PodChaos
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - dev
      labelSelectors:
        app: store-front
    duration: "30s"
